spring:
  application:
    name: ${EUREKA_HOST:eureka-center}
server:
  port: ${EUREKA_PORT:14031}
eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}  #指定该Eureka实例的主机名
    prefer-ip-address: false
  client:
  #  register-with-eureka: false  #Eureka默认也会作为客户端尝试注册，因此需禁用注册行为
   # fetch-registry: false
    serviceUrl:
      defaultZone:  http://${EUREKA_CENTER_HOST:localhost}:${EUREKA_CENTER_PORT:14031}/eureka/