server:
  port: ${SERVER_PORT:14030}
spring:
  application:
    name: ${APPLICATION_NAME:config-server}
  cloud:
    config:
      label: ${CONFIG_LABEL:master} #指明远程仓库的分支
      server:
        git:
          uri: ${SERVER_GIT_URI:https://github.com/xuanfong1/CouldFrame/}   #配置仓库git地址
          search-paths: ${GIT_PATH:config/devrepo}   #配置仓库路径
          username: ${GIT_USERNAME:}   #访问git仓库的用户名，这里因为是开放项目所以不需要设置
          password: ${GTI_PASSWORD:}  #访问git仓库的密码/${EUREKA_CENTER_HOST:localhost}:${EUREKA_CENTER_PORT:14031}/eureka/
#这里也可以注册到eureka注册中心，但是就会存在相互依赖，耦合性不好解决，所以独立出来
eureka:
  client:
    service-url:
      defaultZone:  ${EUREKA_CENTER_REG} #注意要加eureka，不然找不到